---

- name: libselinux-python needed for installation if selinux is enabled
  yum: 
   name: libselinux-python 
   state: present

- name: Install epel repository
  yum: 
   name: epel-release 
   state: latest  

- name: Install ntp packages
  yum:
   name: "{{ item }}"
   state: latest
  with_items:
   - ntp
   - ntpdate

- name: Stop ntp
  service:
   enabled: yes 
   name: ntpd
   state: stopped

- name: Copy default ntp config
  template:
   src: ntp.conf.j2 
   dest: /etc/ntp.conf
   mode: 0644 

- name: set timezone rhel6
  shell: "rm -f /etc/localtime ; ln -s /usr/share/zoneinfo/Europe/Amsterdam /etc/localtime"
  when: centos_version == "6"  

- name: set timezone rhel7
  command: "timedatectl set-timezone {{ ntptimezone }}"
  when: centos_version == "7"  

- name: sync ntp to 0.nl.pool.ntp.org
  command: "ntpdate {{ ntpserv1 }}"

- name: Started ntp
  service:
   name: ntpd
   state: started

- name: Notify hipchat
  hipchat: 
   token: "{{ hipchat_api_token }}" 
   room: "{{ hipchat_room }}" 
   color: purple 
   msg_format: text 
   msg: "ntp is running on {{ ansible_fqdn }}"
  when: hipchat_enabled 