---
#This playbook is to install postgresql with default configuration, nagios and pgstatsinfo monitoring

- hosts: postgresql
  sudo: true
  tasks:
  - name: Update OS before all roles are running
    yum: 
     name: "*" 
     update_cache: yes
     disablerepo: "*"
     enablerepo: "base,updates" 
     state: latest

  - name: libselinux-python needed for installation if selinux is enabled
    yum: 
     name: libselinux-python 
     state: present

  - name: set selinux on enforcing 
    selinux: policy=targeted state=enforcing

  - name: reboot host
    shell: nohup bash -c "sleep 2s && reboot" &

  - name: Wait for server to come back   
    local_action: wait_for port="{{ ansible_port }}" host="{{ ansible_host }}" delay=10 state=started
    sudo: false 

- hosts: postgresql
  sudo: true
  roles:
  - { role: ntp, tags: ntp }
  - { role: postgres, tags: postgres }
  - { role: statistics,  when: pgstatsinfo_enabled, tags: statistics }

